import type { VercelRequest, VercelResponse } from "@vercel/node";
import {
  fetchAllPages,
  getDateRange,
  getProps,
  isValidEvent,
} from "../../lib/calendar/utils.js";
import ical, {
  ICalAlarmType,
  ICalCalendar,
  ICalCalendarMethod,
} from "ical-generator";
import type { NotionResponse } from "../../lib/calendar/types.js";
import { setResponse, verifyParam } from "../../lib/shared/utils.js";
import { isFullPage } from "@notionhq/client";

const createEvent = (page: NotionResponse, cal: ICalCalendar): void => {
  if (!isFullPage(page)) return;

  const props = getProps(page.properties);

  const { date } = props;
  if (!isValidEvent(props, date)) return;

  const { endDate, startDate } = getDateRange(date, props.allDay);

  const event = cal.createEvent({
    allDay: props.allDay,
    description: props.notes,
    end: endDate,
    location: props.place
      ? {
          address: props.place.address ?? undefined,
          geo: { lat: props.place.lat, lon: props.place.lon },
          title: props.place.name ?? undefined,
        }
      : null,
    start: startDate,
    summary: props.title,
    timezone: date.time_zone,
    url: props.url,
  });

  // Alarms: 1h before for timed; 1 day before for all-day
  // We detect all-day either via explicit checkbox or by Notion start lacking time (heuristic)
  event.createAlarm({
    triggerBefore: props.allDay ? 24 * 60 * 60 : 60 * 60,
    type: ICalAlarmType.display,
  });

  // UID & DTSTAMP are auto-generated by ical-generator unless overridden
  event.id(`${page.id}@notion`);
  event.stamp(new Date());
};

const successResponse = (res: VercelResponse, cal: string): void => {
  res.setHeader("Content-Type", "text/calendar; charset=utf-8");
  res.setHeader("Cache-Control", "public, max-age=300");
  res.status(200).send(cal.toString());
};

export default async function handler(
  req: VercelRequest,
  res: VercelResponse,
): Promise<void> {
  try {
    const db = verifyParam(
      res,
      req.query.db,
      "Missing required query param: db",
    );
    const pages = await fetchAllPages(db);

    const cal = ical({
      method: ICalCalendarMethod.PUBLISH,
      name: "Notion Calendar",
    });

    pages.forEach((page) => createEvent(page, cal));
    successResponse(res, cal.toString());
  } catch (error) {
    setResponse({
      error,
      message: "Error generating calendar",
      res,
      status: 500,
    });
  }
}
